# Generated by Django 4.1.3 on 2022-11-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom et prenom')),
                ('profile_type', models.CharField(choices=[('CLIENT', 'Client'), ('FOURNISSEUR', 'Fournisseur'), ('CLIENT_ET_FORUNISSEUR', 'Client et Fournisseur')], max_length=21)),
                ('mobile', models.CharField(max_length=50, verbose_name='nom et prenom')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('password_confirm', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=100, verbose_name='Entreprise')),
            ],
        ),
    ]
