# Generated by Django 4.1.3 on 2022-11-28 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membre',
            old_name='profile_type',
            new_name='type_client',
        ),
    ]
