# Generated by Django 4.1.3 on 2022-11-28 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_facture_article_facture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='Facture',
        ),
    ]
